# Generated by Django 3.2.12 on 2022-03-06 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20220306_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
