# Generated by Django 3.2.12 on 2022-03-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220306_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
