# Generated by Django 3.2.12 on 2022-03-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_slug',
            field=models.SlugField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
